name: Generate grpc server & client
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
      - uses: actions/setup-go@v2
      - name: Download proto libs & setup go env
        run: |
          export GO111MODULE=on
          go get google.golang.org/protobuf/cmd/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          export PATH="$PATH:$(go env GOPATH)/bin"
      - name: Generate server & client
        run: make
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "add changes"
          add: "*.go"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
